python: Development might not be required
jrl-umi3218/jrl-cmakemodules pull request #513
Opened 2022-05-03 18:25 UTC by nim65s

Hi,

In many places, we need only the Python interpreter (and sometimes the include dirs), but libpythonX.Y.so is not necessary.

Building wheel packages allowing distribution on [PyPI](https://pypi.org) even explicitly forbids it (ref. [PEP513](https://peps.python.org/pep-0513/#libpythonx-y-so-1)). Therefore, it is not available on the [manylinux](https://github.com/pypa/manylinux) distribution.

Building jrl-cmakemodules packages on that distribution is currently not working, because CMake consider the `Development` component not found when `libpythonX.Y.so` is not available.

So I think we need to remove that.

Maybe this is required in some other cases I didn't think about yet, so an opt-out option would be better than just this blunt removal. Any idea about that ?

2022-05-23 10:25 UTC, jcarpent requested changes
I would instead suggest making it an optional option or adding a helper to look for it if needed.

2022-05-23 23:15 UTC, nim65s commented
Ok, and would you include or exclude this `Development` component by default ?

2022-05-24 09:59 UTC, jcarpent commented
We can exclude it or use a dedicated JRL_CMAKEMODULE_VAR to say that we are on a PyPi manylinux setup, or detect it automatically.
I would go for the latest solution.

2022-05-30 15:36 UTC, nim65s commented
Here is a solution that will allow for another PR to introduce a manylinux setup which will directly change the default of this `${PYTHON_COMPONENTS}` variable

2022-05-30 16:23 UTC, jcarpent approved these changes

2022-05-30 16:23 UTC, merged